# ==============================================================================
# Ansible Inventory Generated by Terraform local-exec
# ==============================================================================
[webservers]
app-server-01 ansible_host=${instance_ip} ansible_user=${ssh_user} ansible_ssh_private_key_file=${key_file_path}

[all:vars]
deployment_environment=${environment}
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
